-- 2023년 4월 기준 전국 시/도 기준 연령대별 인구수 합계
SELECT AGRDE_SE_CD,
	SUM(POPLTN_CNT) AS AGRDE_POPLTN_CNT
FROM TB_POPLTN
WHERE STD_MT='202304'
	AND ADMINIST_ZONE_NO LIKE '__00000000'
    AND POPLTN_SE_CD = 'T'
GROUP BY AGRDE_SE_CD
ORDER BY AGRDE_SE_CD;