SELECT
	AGRDE_SE_CD,
    ADMINIST_ZONE_NO,
    ADMINIST_ZONE_NM,
    POPLTN_CNT
FROM TB_POPLTN
WHERE ADMINIST_ZONE_NO NOT LIKE '_____00000'
	AND POPLTN_SE_CD = 'T'
    AND STD_MT = '202304'
    AND POPLTN_CNT > 0
ORDER BY PoPLTN_CNT DESC;